### ISSUE TITLE
Release Build failing

### ISSUE THREAD

**Issue by ratz6** [Banuba/quickstart-android#14]
> Task :effect_player_realtime_preview:collectReleaseDependencies FAILED
Execution failed for task ':effect_player_realtime_preview:collectReleaseDependencies'.
> java.io.FileNotFoundException: /home/user/quickstart-android/effect_player_realtime_preview/:banuba_effect_player-release@aar (No such file or directory)

I get an error on release build

**Comment by Gagandeep1408** [comment]
banuba_effect_player-release@aar (No such file or directory)

I'm getting same issue . May I know how this issue can be resolved?
