### ISSUE TITLE
Having too many assets bloats the APK size

### ISSUE THREAD

**Issue by steven0529** [Banuba/quickstart-android#3]
Having too many assets bloats the APK size, how can we add additional effects and trigger only to download a specific effect only when needed? 

Currently I can only find a 

`sdkManager.loadEffects()` and it loads the preloaded effects I placed in assets folder. Is there a way to upload the effects somewhere and access it dynamically to lighten the size of the APK.

**Comment by sdk-banuba** [comment]
Please, follow this guide https://docs.banuba.com/face-ar-sdk/android/android_getting_started#repack-your-sdk-archive-minify-sdk-size
